web/routes.py
from flask import Blueprint, render_template, request, jsonify, flash, send_from_directory, redirect, url_for, Response, session
import hashlib
import time
from . import db
from .models import users, animals, live
import os
import pandas as pd
from . import cam, led
routes = Blueprint('routes', __name__)
from calendar import monthrange

def liveSettings(d_temp,n_temp,d_wet,n_wet,d_start,n_start,mode,name):
	settings = live.query.filter_by(id = 1).first()
	settings.dayTemp = d_temp
	settings.nightTemp = n_temp
	settings.dayWet = d_wet
	settings.nightWet = n_wet
	settings.dayStart = d_start
	settings.nightStart = n_start
	settings.selectedMode = mode
	settings.name = name
	dTemp = settings.dayTemp
	nTemp = settings.nightTemp
	dWet = settings.dayWet
	nWet = settings.nightWet
	dStart = settings.dayStart
	nStart = settings.nightStart
	sMode = settings.selectedMode
	db.session.commit()

@routes.route('/_wykres',methods = ['GET','POST'])
def charts_process():
    df = pd.read_csv('/home/pi/github/webpage/web/.txts/random.csv')
    value = request.args.get('value')
    days = int(request.args.get('time'))
    year = int(request.args.get('year'))
    month = int(request.args.get('month'))
    day = int(request.args.get('day'))
    temp = {}
    if value == 'temp' or value == "wilg" :

        tab = []
        counter = 0
        num_days = monthrange(year, month)[1]
        for _ in range(days):
            if day+counter > num_days:
                if month == 12:
                    month = 1
                    year += 1
                else:
                    month += 1
                counter = 0
                day = 1
            tmp = df.loc[(df['dzienmsc'] == day + counter) & (df['miesiac'] == month) & (df['rok'] == year)]
            tab.append(tmp)
            counter += 1

        tempp = pd.concat(tab)
        if tempp.empty:
            return "false"
        tempp = tempp.to_dict('dict')
        temp[0] = tempp
        return jsonify(temp)

    elif value == 'ruch':
        ruchh = {}
        df = pd.read_csv('/home/pi/github/webpage/web/.txts/motion.csv')
        ruch = df.loc[(df['dzien'] == day) & (df['miesiac'] == month)]
        if ruch.empty:
            return "false"
        ruch = ruch.to_dict('dict')
        ruchh[0] = ruch
        ruchh = jsonify(ruchh)
        return ruchh


@routes.route('/upload_vids/<path:filename>')
def downloadvid(filename):
	vids = "/home/pi/github/webpage/web/Videos/"
	return send_from_directory(vids, filename)

@routes.route('/upload_pics/<path:filename>')
def downloadpic(filename):
	pics = "/home/pi/github/webpage/web/Pictures/"
	return send_from_directory(pics, filename)

@routes.route('/_recording', methods = ['GET','POST'])
def recording():
	if request.method == 'POST':
		time = request.form.get('time')
		cam.recording(int(time))

	return redirect(url_for('routes.home')), flash("Rozpoczęto nagrywanie najbliższych " + time +  " sekund...", category='success')

@routes.route('/_screenshot')
def screenshot():
	cam.takescreen()
	flash("Screenshot zrobiony!", category='success')
	return redirect(url_for('routes.home'))

@routes.route('/_background_process')
def background_proces():
    data = []
    with open('web/.txts/actual.txt', 'r') as f:
        for line in f:
            data.append(line.strip())
    with open('web/.txts/last_motion.txt', 'r') as f:
        last = f.read()
        data.append(last)
    return jsonify(data)

@routes.route('/_ledOn')
def ledOn():
	led.On()
	return redirect(url_for('routes.home'))

@routes.route('/_ledOff')
def ledOff():
	led.Off()
	return redirect(url_for('routes.home'))

@routes.route('/stream')
def stream():
	return Response(cam.generate(), mimetype='multipart/x-mixed-replace; boundary=frame')

@routes.route('/', methods = ['GET', 'POST'])
def home():
    if "user" in session:
        settings = live.query.filter_by(id = 1).first()
        dTemp = settings.dayTemp
        nTemp = settings.nightTemp
        dWet = settings.dayWet
        nWet = settings.nightWet
        dStart = settings.dayStart
        nStart = settings.nightStart
        sMode = settings.selectedMode
        name = settings.name
        record = ""
        if sMode == 1:
            mode = "automatyczny"
        elif sMode == 2:
            mode = "manualny"
        else:
            mode = "niewybrany"

        if request.method != 'POST':
            with open('web/.txts/set.txt', 'w') as f:
                f.write(str(dTemp) + '\n')
                f.write(str(nTemp) + '\n')
                f.write(str(dWet) + '\n')
                f.write(str(dStart) + ":00:00" + '\n')
                f.write(str(nStart) + ":00:00" + '\n')

            return render_template("index.html", user=session["user"],role = session['role'], day_temp = dTemp, night_temp = nTemp, day_wet = dWet, night_wet = nWet, day_start = dStart, night_start = nStart, mode = mode,animalName = name, pointer = led.pointer)
    else:
        flash("Musisz się zalogować", category='error')
        return redirect(url_for("routes.login"))


@routes.route('/wykresy')
def wykresy():
    if "user" in session:
        return render_template("wykresy.html", user=session["user"],role = session['role'])
    else:
        flash("Musisz się zalogować", category='error')
        return redirect(url_for("login"))

@routes.route('/climatesettings',methods = ['GET','POST'])
def climate():
	if "user" in session:
		if request.method != 'POST':
			return render_template("klimat.html", user=session["user"],role = session['role'],animals = animals.query.all(), selectedMode = 1)
		else:
			mode = int(request.form['mode'])

			if mode == 2:
				animal_day_temp = request.form['day_temp']
				animal_night_temp = request.form['night_temp']
				animal_day_wet = request.form['day_wet']
				animal_d_start = request.form['d_start']
				animal_n_start = request.form['n_start']
				liveSettings(animal_day_temp,animal_night_temp,animal_day_wet,10,animal_d_start,animal_n_start,mode,'')

				return render_template("klimat.html",animal_day_temp = animal_day_temp,animal_night_temp = animal_night_temp,animal_day_wet = animal_day_wet,animal_d_start = animal_d_start,animal_n_start = animal_n_start ,user=session["user"],role = session['role'],animals = animals.query.all(), selectedMode = mode)
			else :
				a_id = request.form['id']
				animal = animals.query.filter_by(id=a_id).first()
				name = animal.animal_name
				liveSettings(animal.day_temp,animal.night_temp,animal.day_wet,10, animal.day_start,animal.night_start,mode,name)

				return render_template("klimat.html",animalAuto = animals.query.get(a_id) ,user=session["user"],role = session['role'],animals = animals.query.all(), selectedMode = mode)
	else:
		flash("Musisz się zalogować", category='error')
		return redirect(url_for("routes.login"))


@routes.route('/photos_shots')
def photos_shots():
	if "user" in session:
		picList = os.listdir('/home/pi/github/webpage/web/Pictures')
		vidList = os.listdir('/home/pi/github/webpage/web/Videos')
		picList = sorted(picList, key = lambda x: int(x[10:-4]))
		vidList = sorted(vidList, key = lambda x: int(x[5:-4]))
		return render_template("zdjecia_filmy.html", user=session["user"],role = session['role'], picList = picList, vidList = vidList)
	else:
		flash("Musisz się zalogować", category='error')
		return redirect(url_for("routes.login"))


@routes.route('/settings',methods = ['GET','POST'])
def settings():
    if "user" in session:
        if request.method == 'POST':
            typ = request.args.get('typ')
            if typ == 'zmiana_hasla':
                passw1 = request.form.get('passw1')
                passw2 = request.form.get('passw2')
                if passw1 != passw2:
                    flash("Hasła nie są sobie równe", category='error')
                    return render_template("ustawienia.html", user=session["user"],role = session['role'],users = users.query.all())
                if len(passw1) < 6:
                    flash('Hasło musi składać się z conajmniej 6 znaków', category='error')
                    return redirect(url_for('settings'))
                user_name = request.args.get('user')
                user = users.query.filter_by(username = user_name).first()
                passw = hashlib.sha256(passw1.encode('utf-8'))
                user.password = passw.hexdigest()
                db.session.commit()
                return redirect(url_for('settings'))
            elif typ == 'zmiana_nazwy':
                username = request.form.get('username')
                username2 = request.form.get('username2')
                if username != username2:
                    flash("Nazwy nie są sobie równe", category='error')
                    return render_template("ustawienia.html", user=session["user"],role = session['role'],users = users.query.all())
                user_name = request.args.get('user')
                user = users.query.filter_by(username = user_name).first()
                user.username= username
                db.session.add(user)
                db.session.commit()

                flash('Nazwa użytkownika zmieniona')
                return redirect(url_for('settings'))
        return render_template("ustawienia.html", user=session["user"],role = session['role'],users = users.query.all())
    else:
        flash("Musisz się zalogować", category='error')
        return redirect(url_for("routes.login"))

@routes.route('/see_animals',methods = ['GET','POST'])
def see_animals():
    if "user" in session:
        if request.method != "POST":
            return render_template("zobacz_zwierz.html", user=session["user"],role = session['role'],animals = animals.query.all())

        elif request.form['delete']:
             animal_id = request.form['delete']
             animals.query.filter_by(id=animal_id).delete()
             db.session.commit()
             flash("Usunięto zwierzaka", category='success')

web/templates/base.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='style.css') }}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	
	<style>
        #ruch_div circle{
          opacity: 1;
          fill-opacity: 1;
        }
        #ruch_div > div > div > svg > g:nth-child(4) > path{
          opacity: 0;
        }
      </style>	

        <title>{% block title%}{% endblock %}</title>
    </head>

    <body>
      <nav class="navbar navbar-expand-lg navbar-dark nav_ ">
        <div class="container-fluid">

          <a class="navbar-brand" href="/">Kokpit</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse flex-grow-0 mr-2" id="navbarNav">
            <ul class="navbar-nav">
              {% if user %}
              <li class="nav-item">
                <a class="nav-link" href="/climatesettings"><i class="bi bi-cloud-minus"></i>  Klimat</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="/photos_shots"><i class="bi bi-images"></i> Zdjęcia i filmy</a>
              </li>
	
	     <li class="nav-item">
                <a class="nav-link" href="/wykresy"><i class="bi bi-graph-up"></i> Wykresy</a>
              </li>

              {% if role == 'admin' %}

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Administrator</a>
                <div class="dropdown-menu mr-5">
                  <a class="dropdown-item" href="/signUser">Dodaj użytkownika</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/see_users">Zobacz użytkowników</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/add_animal">Dodaj zwierzaka</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/see_animals">Zobacz zwierzaki</a>
                </div>
              </li>
              {% endif %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{ user }}</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="/settings">Ustawienia</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/logout">Wyloguj się</a>
                </div>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="/signup">Zarejestruj sie</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>


        {% block alert %}
          {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                  {% for category, message in messages %}
                      {% if category == 'error' %}
                      <div class="alert alert-danger alter-dismissable fade show" role="alert">
                          {{ message }}
                          <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        {% else %}
                        <div class="alert alert-success alter-dismissable fade show" role="alert">
                          {{ message }}
                          <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                      {% endif %}
                  {% endfor %}
              {% endif %}
          {% endwith %}
        {% endblock %} 
        
      {% block content %}{% endblock %}

          
      <div class="footer" style="display:none">
        <p><em>PWSZ Gniezno praca inżynierska</em></p> 
      </div>

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    </body>

</html>

web/templates/dodaj_uz.html
{% extends "base.html"%}
{% block title %}Dodawanie użytkownika{% endblock %}

{% block content %}

<div class="container text-center">
    <div class="justify-content-center text-center"></div>
    <form action="{{ request.path }}" method='POST'>
        <br />
        <h2 align = 'center'>Załóż konto</h2>
        <div class="form-group col-md-6 login_row">
            <label for="username">Username</label>
            <input type="username" class="form-control" name='username' id="email" aria-describedby="emailHelp">
        </div>

        <div class="form-group col-md-6 login_row">
            <label for="password">Hasło</label>
            <input type="password" class="form-control" name='password' id="password">
        </div>

        <div class="form-group col-md-6 login_row">
            <label for="password">Powtórz hasło</label>
            <input type="password" class="form-control" name='password2' id="password2">
        </div>

        <div class="form-group col-md-6 login_row">
            <label for="select">Rola</label>
            <select class="form-control" id="exampleFormControlSelect1" name="rola">
                <option value="user">User</option>
                <option value="admin">Admin</option>
                </select>
        </div>

        
        <button type="submit" class="btn btn-success mt-2">Potwierdź</button>
    </form>
    </div>
</div>


{% endblock %}
 

web/templates/dodaj_zwierz.html
{% extends "base.html"%}
{% block title %}Dodaj zwierzaka{% endblock %}
{%block content%}

<div class="container text-center">
  <div class="justify-content-center text-center"></div>
    <form action="{{ request.path }}" method='POST'>
        <br />
        <h2 align = 'center'>Dodaj zwierzaka</h2>
        <div class="form-group col-md-6 login_row text-left">
            <input type="name" class="form-control" name='animalName' id="animalName" required placeholder="Nazwa">
        </div>

        <div id="lista2">
            <div class="input-group mb-3 col-md-6 login_row">
                <div class="input-group-prepend">
                  <span class="input-group-text">Temperatura za dnia:</span>
                </div>
                <input type="text" name="tempD" class="form-control" aria-label="Stopnie Celsjusza (np 23.5)" required>
                <div class="input-group-append">
                  <span class="input-group-text">°C</span>
                </div>
              </div>
        </div>

        <div id="lista2">
            <div class="input-group mb-3 col-md-6 login_row">
                <div class="input-group-prepend">
                  <span class="input-group-text">Temperatura w nocy:</span>
                </div>
                <input type="text" class="form-control" name="tempN" aria-label="Stopnie Celsjusza (np 23.5)" required>  
                <div class="input-group-append">
                  <span class="input-group-text">°C</span>
                </div>
              </div>
        </div>

        <div id="lista2">
            <div class="input-group mb-3 col-md-6 login_row">
                <div class="input-group-prepend">
                  <span class="input-group-text">Wilgotność za dnia:&nbsp&nbsp</span>
                </div>
                <input type="text" class="form-control" name="wetD" aria-label="Wilgotność (np 50)" required>
                <div class="input-group-append">
                  <span class="input-group-text">&nbsp%</span>
                </div>
              </div>
        </div>

        <div id="lista2">
            <div class="input-group mb-3 col-md-6 login_row">
                <div class="input-group-prepend">
                  <label class="input-group-text" for="inputGroupSelect01">Rozpoczęcie trybu dziennego:</label>
                </div>
                <select class="custom-select" id="inputGroupSelect01" name="day_start">
                  <option selected>Wybierz...</option>
                  <option value="0">00:00</option>
                  <option value="1">1:00</option>
                  <option value="2">2:00</option>
                  <option value="3">3:00</option>
                  <option value="4">4:00</option>
                  <option value="5">5:00</option>
                  <option value="6">6:00</option>
                  <option value="7">7:00</option>
                  <option value="8">8:00</option>
                  <option value="9">9:00</option>
                  <option value="10">10:00</option>
                  <option value="11">11:00</option>
                  <option value="12">12:00</option>
                  <option value="13">13:00</option>
                  <option value="14">14:00</option>
                  <option value="15">15:00</option>
                  <option value="16">16:00</option>
                  <option value="17">17:00</option>
                  <option value="18">18:00</option>
                  <option value="19">19:00</option>
                  <option value="20">20:00</option>
                  <option value="21">21:00</option>
                  <option value="22">22:00</option>
                  <option value="23">23:00</option>
                </select>
              </div>
            </div>

            <div id='lista2'>
              <div class="input-group mb-3 col-md-6 login_row">
                <div class="input-group-prepend">
                  <label class="input-group-text" for="inputGroupSelect01">Rozpoczęcie trybu nocnego:</label>
                </div>
                <select class="custom-select" id="inputGroupSelect01" name="night_start">
                  <option selected>Wybierz...</option>
                  <option value="0">00:00</option>
                  <option value="1">1:00</option>
                  <option value="2">2:00</option>
                  <option value="3">3:00</option>
                  <option value="4">4:00</option>
                  <option value="5">5:00</option>
                  <option value="6">6:00</option>
                  <option value="7">7:00</option>
                  <option value="8">8:00</option>
                  <option value="9">9:00</option>
                  <option value="10">10:00</option>
                  <option value="11">11:00</option>
                  <option value="12">12:00</option>
                  <option value="13">13:00</option>
                  <option value="14">14:00</option>
                  <option value="15">15:00</option>
                  <option value="16">16:00</option>
                  <option value="17">17:00</option>
                  <option value="18">18:00</option>
                  <option value="19">19:00</option>
                  <option value="20">20:00</option>
                  <option value="21">21:00</option>
                  <option value="22">22:00</option>
                  <option value="23">23:00</option>
                </select>
              </div>
        </div>

        <div id="lista2"><button type="submit" class="btn btn-success">Zatwierdź</button></div>
    </form>
    </div>
</div>

{%endblock%}

web/templates/index.html
{% extends "base.html"%}
{% block title %}Strona główna{% endblock %}


{% block content%}
<style>
.btn-secondary {padding-left: 100px; padding-right: 100px; margin-left: 20px; margin-right: 80px;}
</style>

 <script type=text/javascript>
        function refresh(){
                $(document).ready(function(){
                        var datalink = "/_background_process";
                        $.getJSON(datalink, {
                                type: "GET",
                                format: "json",
                        })
                        .done(function ( data ) {
                                $("#humidity").html("Wilgotność: " + data[0] + '%');
                                $("#temperature").html("Temperatura: " + data[1] + '\u00B0C');
								$("#last_motion").html("Ostatni ruch: " + data[7]);
				console.log(data);
						})
                });
        };
        setInterval(refresh, 1000);
 </script>

		<div class="container-fluid">

    <div class="row justify-content-center">
        <div id='tytuł'><h1>Strona główna</h1>
            <h3>Witaj, {{user}}</h3> 
            {% if mode == 'automatyczny' %}
            <h4 class="m-auto index_name mt-2">Wybrany tryb dla: <b>{{ animalName }}</b></h4>
            {% elif mode == 'manualny' %}
            <h4 class="m-auto index_name mt-2">Wybrano tryb <b>manualny</b></h4>
            {% endif %}
</div>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-md-3"></div>
        <div class="col-md-6 text-center mb-3 ">
 <form action="/_recording" method="POST">              
 <button class="btn btn-dark"  onclick="window.location.href='{{ url_for('routes.screenshot') }}';"  ><i class="bi bi-camera"></i> Screenshot</button>
                <button class="btn btn-dark ml-2" type="submit" onclick="window.location.href='{{ url_for('routes.recording') }}?document.getElementById('time').value';" ><i class="bi bi-camera-video"></i> Rozpocz. nagrywanie</button>
                <div class="form-group">
    			
<label for="time">Wybierz czas nagrywania</label>
    			<select class="form-control" style="width:25%;margin:auto;" id="time" name="time">
      	<option value="5" >5 sek</option>
      <option value="10" >10 sek</option>
      <option value="15">15 sek</option>
      <option value="30" >30 sek</option>
      <option value="60" >60 sek</option>
    </select>
</form>
  </div>
        </div>
        <div class="col-md-3"></div>
    </div>

    <span id="v1" style="display: none;">
    <div  class="col-md-6 float-left">
	<img class="cam" src="{{url_for('routes.stream')}}">
    </div>
    </span>

	<div class="col-md-3 float-left">
        <div class="row">
            <div class="col-md-12 text-center mt-5 ml-1">
                <p><b>Zadane parametry:</b></p>
                <p>Temperatura za dnia: {{ day_temp }}°C</p>
                <p>Temperatura w nocy: {{ night_temp }}°C</p>
                <p>Wilgotność: {{ day_wet }}%</p>
                <p>Rozpoczęcie trybu dziennego: {{ day_start }}:00</p>
                <p>Rozpoczęcie trybu nocnego: {{ night_start }}:00 </p>
            </div>
        </div>
    </div>
<span id="v2" style="display: block;">
    <div  class="col-md-6 float-left">
        <img class="cam" src="{{url_for('routes.stream')}}">
    </div>
</span>

    <div class="col-md-3 float-left">
     <div class="col-md-12 text-center mt-5">
        <p class="params"><b>Aktualne parametry:</b></p>
        <p class="time">Godzina: <i>czekaj...</i></p>
        <p id='temperature'>Temperatura: <i>czekaj...</i></p>
        <p id='humidity'>Wilgotność: <i>czekaj...</i></p>
		<p id='last_motion'>Ostatni ruch: <i>czekaj...</> </p> 

		{% if pointer == True %}
        <button class="btn btn-dark mb-5" id="led" onclick="window.location.href='{{ url_for('routes.ledOff') }}';"><i class="bi bi-lightbulb-fill"></i>Zgaś światło</button>
		{% else %}
        <button class="btn btn-dark mb-5" id="led" onclick="window.location.href='{{ url_for('routes.ledOn') }}';" ><i class="bi bi-lightbulb"></i>Zapal światło</button>
		{% endif %} 
    </div>
    </div>
</div>

<script>

width = window.innerWidth

console.log(width)

if( width < 770){
  document.getElementById("v2").style.display="none";
  document.getElementById("v1").style.display="block";
}

if(width > 770){
  document.getElementById("v2").style.display="block";
  document.getElementById("v1").style.display="none";
}

var led = document.getElementById("led").innerText;
console.log(led);

function showNotification(){
	const notification = new Notification("Światło",{
		body: "Światło się zapaliło",
		icon: ""});

	notification.onclick = e =>{
		window.location.href = "http://100.121.91.138:2137";
}

}

console.log(Notification.permission);

	if(Notification.permission === "granted"){
		if(led === "Zgaś światło"){
			showNotification();
}}
	else if(Notification.permission !== "denied"){
		Notification.requestPermission().then(permission=>{
			if(permission === 'granted')
				showNotification();})
}

function time(){
    const data = new Date();
    const ele = document.querySelector(".time");

    const html = "Godzina: " + data.getHours() + ":" + data.getMinutes() + ":" + data.getSeconds();
    ele.innerText = html;
    }

     setInterval(time,1000);


if ('serviceWorker' in navigator) {
      window.addEventListener('load', function() {
        navigator.serviceWorker.register("/sw.js", { scope: '/' })
        .then(function(registration) {
          // Registration was successful
          console.log('ServiceWorker registration successful with scope: ', registration.scope);
        }, function(err) {
          // registration failed :(
          console.log('ServiceWorker registration failed: ', err);
        });
      });
    } 




</script>

</div>
{% endblock %}

web/templates/login.html
{% extends "base.html" %}
{% block title %}Logowanie{% endblock %}
 
{% block content %}

<div class="container ">
    <div class="justify-content-center text-center">
    <form action="{{ request.path }}" method='POST'>
        <br />
        <h2 align = 'center'>Zaloguj się</h2>
        <div class="form-group col-md-6 login_row">
            <label for="login">Login</label>
            <input type="text" class="form-control" name='username' id="floatingInput"  required autofocus>
        </div>
        <div class="form-group col-md-6 login_row">
            <label for="password">Hasło</label>
            <input type="password" class="form-control" name='password' id="password" required>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Potwierdź</button>
    </form>
</div></div>
{% endblock %}

web/templates/zdjecia_filmy.html
{% extends "base.html"%}
{% block title %}Zdjęcia i filmy{% endblock %}
{%block content%}
<div class="container">
<div class="justify-content-center text-center">
<div class="col-md-10 m-auto">
<div class="row mt-3" style="display:inherit !important; float:left;">
<h2>Lista zdjęć</h2>
{% for element in picList  %}
<div class="screenshot_div mt-2" style="float:left;width:25%;padding-right:1%;padding-left:1%;">
<img src="{{ url_for('routes.downloadpic', filename= element) }}" style="width:100%">
<figcaption>
<a class="screenshot_element" style="word-break: break-word;color:white !important;"  href="{{ url_for( 'routes.downloadpic', filename = element ) }}">{{element}}</a>
</figcaption>
</div>
{%endfor%}
</div>
<div class="row mt-3" style="display:inherit !important;">
<h2>Lista filmów</h2>
{% for element in vidList  %}
<div class="video_div mt-2" style="float:left; width:25%; padding-right:1%;padding-left:1%;">
<video width="100%" height="100%" controls>
<source src="{{ url_for('routes.downloadvid', filename = element) }}" >
<a class ="video_element"  href="{{ url_for( 'routes.downloadvid', filename = element ) }}">{{element}}</a>
</video>
<a class="video_element" style="color:white !important" href="{{ url_for( 'routes.downloadvid', filename = element ) }}">{{element}}</a>
</div>
{%endfor%}
</div>
</div>
</div>
{%endblock%}